aluno:
  profile:
    images:
      directory: src/main/resources/static/images/alunos

img:
  profile:
    default: src/main/resources/static/images/profile_default.png
 
instrutor:
  profile:
    images:
      directory: src/main/resources/static/images/instrutores

spring:
  datasource:
    url: jdbc:h2:mem:acaddb
    username: iamm
    password: 1221
    driverClassName: org.h2.Driver
  jpa:
    show-sql: false
    open-in-view: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
      data-locations: classpath:data.sql
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 20MB
      max-request-size: 20MB